return {}
-- return {
--   'yetone/avante.nvim',
--   event = 'VeryLazy',
--   lazy = false,
--   version = false, -- set this if you want to always pull the latest change
--   build = 'make',
--   dependencies = {
--     'stevearc/dressing.nvim',
--     'nvim-lua/plenary.nvim',
--     'MunifTanjim/nui.nvim',
--     --- The below dependencies are optional,
--     'hrsh7th/nvim-cmp', -- autocompletion for avante commands and mentions
--     'nvim-tree/nvim-web-devicons', -- or echasnovski/mini.icons
--     {
--       -- Make sure to set this up properly if you have lazy=true
--       'MeanderingProgrammer/render-markdown.nvim',
--       opts = {
--         file_types = { 'markdown', 'Avante' },
--       },
--       ft = { 'markdown', 'Avante' },
--     },
--   },
--   config = function()
--     require('avante_lib').load()
--     require('avante').setup {
--       claude = {
--         disable_tools = true, -- Disable tools for now (it's enabled by default) as it's causing rate-limit problems with Claude, see more here: https://github.com/yetone/avante.nvim/issues/1384
--       },
--     }
--   end,
-- }
